---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-key:reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["porkbun-key"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook:key-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-key:reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun-webhook
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: porkbun-webhook-list-prioritylevelconfigurations
rules:
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - prioritylevelconfigurations
  - flowschemas
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: porkbun-webhook-list-prioritylevelconfigurations
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: porkbun-webhook-list-prioritylevelconfigurations
  apiGroup: rbac.authorization.k8s.io

